# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false
    config.vm.define :Balanceador do |node1|
    node1.vm.box = "centos1706_v0.2.0_rabbitmq_sensu_guestadditions"
    node1.vm.network :private_network, ip: "192.168.56.101"
    node1.vm.provider :virtualbox do |vb1|
      vb1.customize ["modifyvm", :id, "--memory", "1024","--cpus", "1", "--name", "Balanceador" ]
    end
    config.vm.provision "chef_solo" do |chef|
       chef.cookbooks_path = "cookbooks"
       chef.add_recipe "balanceador"
       chef.json = {
        "web_servers" => [
          {"ip":"192.168.56.102"},{"ip":"192.168.56.103"}
         ]
       }
    end
  end


  config.vm.define :server_web_1 do |node2|
    node2.vm.box = "centos1706_v0.2.0_rabbitmq_sensu_guestadditions"
    node2.vm.network :private_network, ip: "192.168.56.102"
    node2.vm.provider :virtualbox do |vb2|
      vb2.customize ["modifyvm", :id, "--memory", "512","--cpus", "1", "--name", "server_web_1" ]
    end
    config.vm.provision "chef_solo" do |chef|
       chef.cookbooks_path = "cookbooks"
       chef.add_recipe "httpd"
       chef.json = {
         "servidor" => "Servidor 1",
	  "ip" => "192.168.56.102"
		   }
    end
  end

 config.vm.define :server_web_2 do |node3|
    node3.vm.box = "centos1706_v0.2.0_rabbitmq_sensu_guestadditions"
    node3.vm.network :private_network, ip: "192.168.56.103"
    node3.vm.provider :virtualbox do |vb3|
      vb3.customize ["modifyvm", :id, "--memory", "512","--cpus", "1", "--name", "server_web_2" ]
    end
    config.vm.provision "chef_solo" do |chef|
       chef.cookbooks_path = "cookbooks"
       chef.add_recipe "httpd"
       chef.json = {
         "servidor" => "Servidor 2",
         "ip" => "192.168.56.103"
       }
    end
  end
end
